oabs:
  datasource: # 数据库配置信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: oabs
    username: root
    password: 1234
  jwt:
    secret-key: 12345678123456781234567812345678
    expiration-time: 172800000